from zstarview.aircraft_constants import AIRCRAFT_OVERLAY_LINE_COLOR_RGB
from zstarview.paths import (
    HORIZON_LINE_COLOR,
    PALETTE_AIRCRAFT_AND_SATELLITE_RGB,
    PALETTE_ASTERISM_RGB,
    PALETTE_EARTH_GUIDE_RGB,
    PALETTE_HORIZON_AND_LABEL_RGB,
    PALETTE_TERRAIN_HORIZON_RGB,
    TERRAIN_HORIZON_LINE_COLOR,
)
from zstarview.satellite_constants import SATELLITE_OVERLAY_MARKER_COLOR_RGB


def test_overlay_colors_follow_the_palette_swatches() -> None:
    assert PALETTE_EARTH_GUIDE_RGB == (112, 99, 89)
    assert PALETTE_TERRAIN_HORIZON_RGB == (216, 206, 192)
    assert TERRAIN_HORIZON_LINE_COLOR == PALETTE_TERRAIN_HORIZON_RGB
    assert HORIZON_LINE_COLOR == PALETTE_HORIZON_AND_LABEL_RGB
    assert PALETTE_AIRCRAFT_AND_SATELLITE_RGB == (249, 130, 255)
    assert AIRCRAFT_OVERLAY_LINE_COLOR_RGB == PALETTE_AIRCRAFT_AND_SATELLITE_RGB
    assert SATELLITE_OVERLAY_MARKER_COLOR_RGB == PALETTE_AIRCRAFT_AND_SATELLITE_RGB
    assert PALETTE_ASTERISM_RGB == (122, 226, 240)
