"""Shared constants for the planned OpenSky aircraft overlay."""

AIRCRAFT_MIN_EAST_WEST_COVERAGE_KM = 90.0
AIRCRAFT_REFRESH_INTERVAL_SECONDS = 5 * 60
AIRCRAFT_PREDICTION_REFRESH_INTERVAL_SECONDS = 2
AIRCRAFT_TRAIL_HALF_SPAN_SECONDS = 4.0
AIRCRAFT_BBOX_DELTA_DEG = 1.0
AIRCRAFT_FADE_START_SECONDS = 90.0
AIRCRAFT_FADE_END_SECONDS = 300.0
AIRCRAFT_MIN_ALPHA_SCALE = 70.0 / 230.0
AIRCRAFT_BBOX_MAX_AREA_SQ_DEG = 25.0

# OpenSky credits for `/states/all` are based on bbox area in square degrees.
AIRCRAFT_BBOX_AREA_SQ_DEG = (AIRCRAFT_BBOX_DELTA_DEG * 2.0) ** 2
