from __future__ import annotations

from .terrain.horizon import DEFAULT_TERRAIN_DISTANCE_BAND_EDGES_KM

NIGHT_LIGHTS_DATASET_VERSION = "2025_vnl_v22_average_masked"
NIGHT_LIGHTS_MANIFEST_URL = (
    "https://github.com/tos-kamiya/zstarview/releases/download/"
    "night-lights-2025/manifest.json"
)
NIGHT_LIGHTS_TILE_NAMES = ("A1", "A2", "B1", "B2", "C1", "C2", "D1", "D2")
NIGHT_LIGHTS_TILE_COUNT = len(NIGHT_LIGHTS_TILE_NAMES)
NIGHT_LIGHTS_TILE_WIDTH_DEG = 90.0
NIGHT_LIGHTS_TILE_HEIGHT_DEG = 90.0
NIGHT_LIGHTS_MAX_DISTANCE_KM = 128.0
# Keep the ray sampling interval close to the native VNL pixel scale instead
# of skipping several hundred-metre pixels at each sample.
NIGHT_LIGHTS_DISTANCE_STEP_KM = 1.0
NIGHT_LIGHTS_AZIMUTH_SIGMA_SCALE = 0.75
NIGHT_LIGHTS_BAND_CENTER_OFFSET_DEG = 1.5
NIGHT_LIGHTS_BAND_HALF_WIDTH_DEG = 1.5
NIGHT_LIGHTS_MAX_ALPHA = 0.48
NIGHT_LIGHTS_GLOW_RGB = (244, 246, 248)
NIGHT_LIGHTS_SUN_BLEND_START_ALT_DEG = -9.0
NIGHT_LIGHTS_SUN_BLEND_END_ALT_DEG = -4.0
NIGHT_LIGHTS_DISTANCE_BAND_EDGES_KM = DEFAULT_TERRAIN_DISTANCE_BAND_EDGES_KM[1:]
NIGHT_LIGHTS_NEIGHBORHOOD_SIGMA_DEG = 6.0
NIGHT_LIGHTS_DISTANCE_SIGMA_GAMMA = 0.65
# Keep the visual distance-smearing reference stable when the ray sampling
# interval changes.
NIGHT_LIGHTS_DISTANCE_SIGMA_REFERENCE_M = 3000.0
NIGHT_LIGHTS_LOG_COMPRESSION_STRENGTH = 0.5
NIGHT_LIGHTS_NEIGHBORHOOD_MAX_AZ_DELTA_DEG = 25.0
NIGHT_LIGHTS_NEIGHBORHOOD_CHUNK_SIZE = 4096
NIGHT_LIGHTS_NEIGHBORHOOD_WEIGHT_STEP_DEG = 0.5
NIGHT_LIGHTS_ALTITUDE_MIN_DEG = -90.0
NIGHT_LIGHTS_ALTITUDE_MAX_DEG = 90.0
NIGHT_LIGHTS_ALTITUDE_STEP_DEG = 1.0
