"""Shared constants for artificial satellite data retrieval and cache."""

from .aircraft_constants import AIRCRAFT_PREDICTION_REFRESH_INTERVAL_SECONDS

SATELLITE_POSITION_REFRESH_INTERVAL_SECONDS = AIRCRAFT_PREDICTION_REFRESH_INTERVAL_SECONDS
SATELLITE_ELEMENT_VALID_SECONDS = 6 * 60 * 60
SATELLITE_ELEMENT_REFRESH_INTERVAL_SECONDS = SATELLITE_ELEMENT_VALID_SECONDS
SATELLITE_ARCHIVE_RETENTION_SECONDS = 3 * 24 * 60 * 60
