"""Shared constants for artificial satellite data retrieval and cache."""

from .aircraft_constants import AIRCRAFT_PREDICTION_REFRESH_INTERVAL_SECONDS

SATELLITE_POSITION_REFRESH_INTERVAL_SECONDS = AIRCRAFT_PREDICTION_REFRESH_INTERVAL_SECONDS
SATELLITE_ELEMENT_REFRESH_INTERVAL_SECONDS = 24 * 60 * 60
