"""Shared constants for artificial satellite data retrieval and cache."""

from .aircraft_constants import AIRCRAFT_PREDICTION_REFRESH_INTERVAL_SECONDS
from .paths import PALETTE_AIRCRAFT_AND_SATELLITE_RGB

SATELLITE_ISS_CACHE_KEY = "iss"
SATELLITE_HORIZONS_CACHE_KEY = "horizons"
SATELLITE_GROUP_VALIDITY_SECONDS = {
    SATELLITE_ISS_CACHE_KEY: 24 * 60 * 60,
    SATELLITE_HORIZONS_CACHE_KEY: 24 * 60 * 60,
}
SATELLITE_MIN_REFRESH_INTERVAL_SECONDS = min(SATELLITE_GROUP_VALIDITY_SECONDS.values())
SATELLITE_FETCH_TIMEOUT_SECONDS = 60.0
SATELLITE_FAILURE_RETRY_SECONDS = 2 * 60 * 60
SATELLITE_POSITION_REFRESH_INTERVAL_SECONDS = AIRCRAFT_PREDICTION_REFRESH_INTERVAL_SECONDS
SATELLITE_ELEMENT_VALID_SECONDS = SATELLITE_MIN_REFRESH_INTERVAL_SECONDS
SATELLITE_ELEMENT_REFRESH_INTERVAL_SECONDS = SATELLITE_MIN_REFRESH_INTERVAL_SECONDS
SATELLITE_OVERLAY_MARKER_COLOR_RGB = PALETTE_AIRCRAFT_AND_SATELLITE_RGB
SATELLITE_OVERLAY_MARKER_MAX_ALPHA = 255
